MeteoStorm.InfoHub/Models/Access/LoginModel.cs
using System.ComponentModel.DataAnnotations;

namespace MeteoStorm.InfoHub.Models.Access
{
  public class LoginModel
  {
    [Display(Name = "Login"), Required(ErrorMessage = "Enter login")]
    [MaxLength(32, ErrorMessage = "Maximum length for login is 32 characters")]
    public string Login { get; set; }

    [Display(Name = "Password"), Required(ErrorMessage = "Enter password")]
    [MaxLength(16, ErrorMessage = "Maximum length for password is 16 characters")]
    [DataType(DataType.Password)]
    public string Password { get; set; }

    public string ErrorMessage { get; set; }
  }
}

MeteoStorm.InfoHub/Models/Home/ErrorViewModel.cs
namespace MeteoStorm.InfoHub.Models.Home
{
  public class ErrorViewModel
  {
    public string RequestId { get; set; }
    public string ErrorMessage { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
  }
}

MeteoStorm.InfoHub/Controllers/AccessController.cs
using Microsoft.AspNetCore.Mvc;
using MediatR;
using MeteoStorm.InfoHub.Models.Access;
using MeteoStorm.InfoHub.MediatR.Access.Commands;

namespace MeteoStorm.InfoHub.Controllers
{
  public class AccessController : BaseController
  {
    public AccessController(IMediator mediator) : base(mediator) { }

    [HttpGet]
    public IActionResult Login()
    {
      var user = HttpContext.User;
      if (user.Identity.IsAuthenticated)
        return RedirectToAction("Index", "Home");

      return View();
    }

    [HttpPost]
    public async Task<IActionResult> Login(LoginModel model)
    {
      if (!ModelState.IsValid)
        return View(model);

      var result = await _mediator.Send(new LoginCommand(model));
      if (string.IsNullOrEmpty(result.ErrorMessage))
        return RedirectToAction("Index", "Home");
      else
        return View(result);
    }

    [HttpGet]
    public async Task<IActionResult> Logout()
    {
      await _mediator.Send(new LogoutCommand());
      return RedirectToAction("Login");
    }

    [HttpGet]
    public IActionResult AccessDenied()
    {
      return View();
    }
  }
}

MeteoStorm.InfoHub/Controllers/BaseController.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;

namespace MeteoStorm.InfoHub.Controllers
{
  public class BaseController : Controller
  {
    protected readonly IMediator _mediator;

    public BaseController(IMediator mediator)
    {
      _mediator = mediator;
    }
  }
}

MeteoStorm.InfoHub/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Diagnostics;
using MeteoStorm.InfoHub.Authorization;
using MeteoStorm.InfoHub.Models.Home;

namespace MeteoStorm.InfoHub.Controllers
{
  [Authorize(Policy = Policies.Employees)]
  public class HomeController : Controller
  {
    [HttpGet]
    public IActionResult Index()
    {
      return View();
    }

    [HttpGet]
    public IActionResult Privacy()
    {
      return View();
    }

    [HttpGet]
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
      var exceptionHandlerPathFeature = HttpContext.Features.Get<IExceptionHandlerPathFeature>();
      var exception = exceptionHandlerPathFeature?.Error;

      var errorViewModel = new ErrorViewModel
      {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier,
        ErrorMessage = exception?.Message
      };

      return View(errorViewModel);
    }
  }
}

MeteoStorm.InfoHub/Views/Access/AccessDenied.cshtml
@{
  ViewData["Title"] = "Access denied";
}

<h1>Access denied</h1>
<p>You are not authorized to access this resource</p>

MeteoStorm.InfoHub/Views/Access/Index.cshtml
@page
@model MeteoStorm.InfoHub.Views.Access.IndexModel
@{
}

MeteoStorm.InfoHub/Views/Access/Login.cshtml
@model MeteoStorm.InfoHub.Models.Access.LoginModel;

@{
  ViewData["Title"] = "Login";
}

<div class="d-flex justify-content-center align-items-center mt-5">
  <div class="card" style="width: 20rem;">
    <div class="card-header">
      <h5 class="mb-0 text-center card-title">Sign in to your account</h5>
      </div>
        <div class="d-flex justify-content-center align-items-center p-3">
        @using (Html.BeginForm("Login", "Access"))
        {
          @Html.AntiForgeryToken()

          <div class="form-group">
            @Html.LabelFor(model => model.Login, new { @class = "control-label" })
            @Html.TextBoxFor(x => x.Login, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Login, null, new { @class = "text-danger" })
          </div>

          <div class="form-group">
            @Html.LabelFor(model => model.Password, new { @class = "control-label" })
            @Html.PasswordFor(x => x.Password, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Password, null, new { @class = "text-danger" })
          </div>

          <button type="submit" class="btn btn-primary">Login</button>

          @if (Model != null && !string.IsNullOrEmpty(Model.ErrorMessage))
          {
            <div class="alert alert-danger">@Model.ErrorMessage</div>
          }
        }
      </div>
  </div>
</div>


@section scripts {
  <partial name="_ValidationScriptsPartial" />

  <script>
    $('form').submit(function () {
      $('.alert-danger').hide();
    });
  </script>
}

MeteoStorm.InfoHub/Views/Home/Index.cshtml
@{
  ViewData["Title"] = "Home Page";
}

<div class="text-center">
  <h1 class="display-4">Welcome</h1>
  <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MeteoStorm.InfoHub/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>@ViewData["Title"] - MeteoStorm.InfoHub</title>
  <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
  <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
  <link rel="stylesheet" href="~/css/main.css" />
</head>
<body>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MeteoStorm</a>
      <div class="justify-content-end" id="navbarNavDropdown">
        @if (User.Identity.IsAuthenticated)
        {
          <ul class="navbar-nav">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                @User.Identity.Name
              </a>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuLink" data-bs-dropdown>
                <a class="dropdown-item" asp-area="" asp-controller="Access" asp-action="Logout">Log Out</a>
              </div>
            </li>
          </ul>
        }
      </div>
    </div>
  </nav>
  <div class="container-fluid">
    <div class="row">
      @if (User.Identity.IsAuthenticated)
      {
        <nav class="navbar navbar-expand-md navbar-light bg-light col-md-2 flex-md-column">
          <ul class="navbar-nav flex-md-column w-100">
            <li class="nav-item active">
              <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </li>
          </ul>
        </nav>
      }
      <main role="main" class="col-md-10 ml-md-auto px-4 mt-3">
        @RenderBody()
      </main>
    </div>
  </div>
  <script src="~/lib/jquery/dist/jquery.min.js"></script>
  <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
  <script src="~/js/site.js" asp-append-version="true"></script>
  @await RenderSectionAsync("Scripts", required: false)
</body>
</html>